# -*- coding: utf-8 -*-
"""Legal_Document_Summarizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19UcpO_EzMjOUOo-2cpEXu9qkDD461g0Y
"""

!pip install transformers torch pdfplumber deep-translator gradio spacy
!python -m spacy download en_core_web_sm

import pdfplumber
import re
import spacy
from transformers import pipeline
from deep_translator import GoogleTranslator
import gradio as gr

# Improved text extraction with OCR fallback (partial implementation)
def extract_text(pdf_path):
    try:
        with pdfplumber.open(pdf_path) as pdf:
            text = " ".join([page.extract_text() for page in pdf.pages if page.extract_text()])
        return text if text else "Error: No extractable text."
    except:
        return "Error: Unsupported PDF format (scanned?)."

# Dynamic legal term detection using spaCy
nlp = spacy.load("en_core_web_sm")
def detect_legal_terms(text):
    doc = nlp(text)
    legal_terms = [ent.text for ent in doc.ents if ent.label_ in ["LAW", "DATE", "ORG"]]
    return list(set(legal_terms))

# Highlighting with dynamic terms
def highlight(text):
    terms = detect_legal_terms(text) + ["liability", "termination"]  # Hybrid approach
    for term in terms:
        text = re.sub(rf'\b({term})\b', r'<mark>\1</mark>', text, flags=re.IGNORECASE)
    return text

# Summarization with BART (or switch to legal-BERT)
summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

def process_pdf(pdf_file, language):
    text = extract_text(pdf_file.name)
    if "Error" in text: return text, ""

    summary = summarizer(text, max_length=300, min_length=150)[0]['summary_text']
    highlighted = highlight(summary)

    if language != "English":
        try: highlighted = GoogleTranslator(source='en', target=language).translate(highlighted)
        except: return "Translation failed", ""

    return summary, highlighted

# Gradio Interface
interface = gr.Interface(
    fn=process_pdf,
    inputs=[gr.File(label="Upload PDF"), gr.Dropdown(["English", "Hindi", "Tamil"], label="Language")],
    outputs=[gr.Textbox(label="Summary"), gr.HTML(label="Highlighted Summary")],
    title="Legal Document Summarizer",
    allow_flagging="never"
)

interface.launch(share=True)